FROM python:3.7-buster
RUN apt-get update && apt-get install nginx vim -y --no-install-recommends
COPY requirements.txt /opt/app/
WORKDIR /opt/app
#COPY .pip_cache /opt/app/pip_cache/
RUN pip install -r requirements.txt --cache-dir /opt/app/pip_cache
