from unicodedata import name
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('api/register/<int:group_id>/', register_api, name='register_api'),
    path('api/login/', login_api, name='login_api'),
    path('api/register/<str:key>/', register_api, name='register_api'),
    path('api/register/<str:key>/<int:user_id>/', register_api, name='register_api'),
    path('api/course/', update_course_details, name='update_course_details'),
    path('api/experience/', update_experience, name='update_experience'),
    path('api/upload_file/', upload_file_api, name='upload_file_api'),
    path("api/get/course-by-id/<int:course_id>/", course_by_id, name="course-by-id"),
    path("api/get/course-by-type/<str:course_type>/",course_by_type, name="course_by_type"),
    path('create-order/', create_order),
    path('payment-success/', payment_success, name='payment_success'),
    path('payment-failure/', payment_failure, name='payment_failure'),
    path("invoice-generate/<int:course_id>/", invoice_generate, name="invoice"),
    path("email-invoice/", emailInvoice, name="email-invoice"),
    path("send-guest-otp/", send_guest_otp, name="send_guest_otp"),
    path("verify-guest-otp/", verify_guest_otp, name="verify_guest_otp"),

    path('', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('courses/', courses, name="courses"),
    path('register/<int:group_id>/', register_view, name='register'),
    path('candidate-search/',candidate_search_api,name='candidate_search_api'),
    path('toggle-course-group-status/',toggle_course_group_status,name='toggle_course_group_status'),
    # path('register/<str:message>/', register_view, name='register'),
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('login/<str:message>/', login_view, name='login_view'),
    path('api/verify-otp/', verify_login_otp),
    path('api/resend-otp/', resend_otp),
    path('profile/', profile_view, name='profile_view'),
    path('profile/<int:user_id>/', profile_view, name='profile_view'),
    path('zip_download/<int:user_id>/', download_view, name='download_view'),
    path('experience/<int:experience_id>/', edit_experience, name='edit_experience'),
    path('delete-experience/<int:experience_id>/', delete_experience, name='delete_experience'),
    path('password_change/', change_password, name="change-password"),
    path('change_password_api/', change_password_submit, name="change-password-api"),
    path('terms-and-conditions/', terms, name="terms"),
    path('privacy-policy/', privacy, name="privacy"),
    path('cancellation-policy/', cancellation, name="cancellation"),
    path('refund-policy/', refund, name="refund"),
    path('create-course-group/', create_course_group, name="create-course-group"),
    path('assign-candidates-group/', assign_candidates_group, name="assign_candidates_group"),
    path('assign-admins-group/', assign_admins_group, name='assign_admins_group'),
]
