# Generated by Django 5.2.1 on 2025-05-25 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_title', models.TextField(default='', null=True)),
                ('file_location', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_level', models.TextField(default='', null=True)),
                ('course', models.TextField(default='', null=True)),
                ('specialization', models.TextField(default='', null=True)),
                ('college', models.TextField(default='', null=True)),
                ('university', models.TextField(default='', null=True)),
                ('year_in', models.TextField(default='', null=True)),
                ('year_out', models.TextField(default='', null=True)),
                ('percentage', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.TextField(default='', null=True)),
                ('designation', models.TextField(default='', null=True)),
                ('domain', models.TextField(default='', null=True)),
                ('date_in', models.TextField(default='', null=True)),
                ('date_out', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(default='CANDIDATE', max_length=300, null=True)),
                ('pan_name', models.CharField(default='', max_length=300, null=True)),
                ('phone_number', models.CharField(default='', max_length=300, null=True)),
                ('whatsapp_number', models.CharField(default='', max_length=300, null=True)),
                ('dob', models.CharField(default='', max_length=300, null=True)),
                ('father', models.CharField(default='', max_length=300, null=True)),
                ('mother', models.CharField(default='', max_length=300, null=True)),
                ('aadhar', models.CharField(default='', max_length=300, null=True)),
                ('pan', models.CharField(default='', max_length=300, null=True)),
                ('passport', models.CharField(default='', max_length=300, null=True)),
                ('marital', models.CharField(default='', max_length=300, null=True)),
                ('gender', models.CharField(default='', max_length=300, null=True)),
                ('blood', models.CharField(default='', max_length=300, null=True)),
                ('batch', models.CharField(default='', max_length=300, null=True)),
                ('batch_month', models.CharField(default='', max_length=300, null=True)),
                ('batch_timings', models.CharField(default='', max_length=300, null=True)),
                ('batch_year', models.CharField(default='', max_length=300, null=True)),
                ('reference', models.CharField(default='', max_length=300, null=True)),
                ('profile_image', models.TextField(default='DEFAULT_IMAGE')),
                ('interests', models.TextField(default='', null=True)),
                ('skill_set', models.CharField(default='', max_length=300, null=True)),
                ('about', models.TextField(default='', null=True)),
                ('present_address', models.TextField(default='', null=True)),
                ('permanent_address', models.TextField(default='', null=True)),
                ('uan', models.TextField(default='', null=True)),
                ('profile_status', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
