# Generated by Django 5.2.1 on 2025-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_documents_file_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('DevOps', 'DevOps'), ('Full stack', 'Full stack')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('course_concept', models.TextField(blank=True, default='', null=True)),
                ('course_eligibility', models.TextField(blank=True, default='', null=True)),
                ('course_format', models.TextField(blank=True, default='', null=True)),
                ('course_slogan', models.TextField(blank=True, default='', null=True)),
                ('keywords', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='courses')),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
