# Generated by Django 5.2.2 on 2025-06-07 20:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_payment_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_link',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='invoices-pdf'),
        ),
    ]
