# Generated by Django 5.2.2 on 2026-04-20 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_payment_userid_payment_address_payment_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loginotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login Verification'), ('email_verification', 'Email Verification (Course Purchase)')], default='login', max_length=30),
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
