# Generated by Django 5.2.2 on 2026-04-24 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_loginotp_email_loginotp_purpose_alter_loginotp_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='otp',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='loginotp',
            index=models.Index(fields=['user'], name='home_logino_user_id_90a622_idx'),
        ),
        migrations.AddIndex(
            model_name='loginotp',
            index=models.Index(fields=['email'], name='home_logino_email_0f658d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginotp',
            index=models.Index(fields=['created_at'], name='home_logino_created_012ddc_idx'),
        ),
    ]
