# Generated by Django 5.2.2 on 2026-04-27 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_candidategroup_profile_candidate_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateGroup',
            new_name='CourseGroup',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='candidate_group',
            new_name='course_group',
        ),
    ]
