# Generated by Django 5.2.2 on 2026-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_candidategroup_coursegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='created_by',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
