# Generated by Django 5.2.2 on 2026-05-19 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_coursegroup_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='admin_course_group',
            field=models.ManyToManyField(blank=True, related_name='admin_course_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
